// Generated by CoffeeScript 1.6.3
(function() {
  var data, multireddit, ui;

  data = require('data');

  ui = require('ui');

  multireddit = new data.MultiReddit(function() {
    return ui.resetPostRows(multireddit.posts);
  });

  Ti.App.addEventListener('subreddits_changed', function(e) {
    multireddit.subreddits = Ti.App.Properties.getList('subreddits', []);
    return multireddit.refreshPosts();
  });

  multireddit.appInit();

  multireddit.refreshPosts();

}).call(this);