// Generated by CoffeeScript 1.6.3
(function() {
	var addSubreddits, btn, opts, removeSubreddit, subreddits, tableData, tableView, tf, topView, win2;

	subreddits = Ti.App.Properties.getList('subreddits', []);

	addSubreddits = function(newSubreddits) {
		subreddits = subreddits.concat(newSubreddits);
		return Ti.App.Properties.setList('subreddits', subreddits);
	};

	removeSubreddit = function(subreddit) {
		subreddits = subreddits.filter(function(value) {
			if (value !== subreddit) {
				return true;
			} else {
				return false;
			}
		});
		Ti.App.Properties.setList('subreddits', subreddits);
		return Ti.App.fireEvent('subreddits_changed');
	};

	tableData = function() {
		var data, subreddit, _i, _len;
		data = [];
		for ( _i = 0, _len = subreddits.length; _i < _len; _i++) {
			subreddit = subreddits[_i];
			data.push({
				title : subreddit
			});
		}
		return data;
	};

	if (subreddits.length === 0) {
		addSubreddits(['aww', 'wow', 'pics', 'doge']);
	}

	win2 = Ti.UI.createWindow({
		title : 'Add a Subreddit',
		backgroundColor : '#fff',
		layout : ' vertical'
	});

	topView = Ti.UI.createView({
		layout : 'horizonal',
		height : 70,
		top : 10,
		width : Ti.UI.FILL
	});

	tf = Ti.UI.createTextField({
		borderStyle : Ti.UI.INPUT_BORDERSTYLE_ROUNDED,
		height : 60,
		width : 350,
		top : 10,
		left : 10,
		hintText : 'Add a Subreddit'
	});

	btn = Ti.UI.createButton({
		title : 'Add',
		top : 10,
		right : 10,
		width : 100,
		height : 60
	});

	tableView = Ti.UI.createTableView({
		top : 80,
		data : tableData()
	});

	btn.addEventListener('click', function(e) {
		var input;
		input = tf.value;
		addSubreddits([input]);
		tf.value = '';
		tf.blur();
		tableView.setData(tableData());
		return alert('Subreddit Added');
	});

	opts = {
		cancel : 2,
		options : ['Edit', 'Delete', 'Cancel'],
		selectedIndex : 2,
		destructive : 1,
		title : 'Edit Subreddit'
	};

	tableView.addEventListener('click', function(e) {
		var dialog, subreddit;
		subreddit = e.rowData.title;
		dialog = Ti.UI.createOptionDialog(opts);
		dialog.addEventListener('click', function(e) {
			if (e.index === 0) {

			} else if (e.index === 1) {
				removeSubreddit(subreddit);
				tableView.setData(tableData());
				return alert('Subreddit deleted!');
			}
		});
		return dialog.show();
	});

	topView.add(tf);

	topView.add(btn);

	win2.add(topView);

	win2.add(tableView);

	exports.win = win2;

}).call(this);